-- ============================================================================
-- tweetforme / echo — core schema
-- ----------------------------------------------------------------------------
-- This is the "script that matches the database to the frontend". The columns
-- on `posts` line up 1:1 with what content-pipeline.html reads and writes, and
-- the extra columns power the orchestration layer (approval gating + auto-post).
--
-- Run with:  supabase db push        (or paste into the SQL editor)
-- Safe to re-run: everything is `if not exists` / idempotent.
-- ============================================================================

create extension if not exists pgcrypto;  -- gen_random_uuid()

-- ── updated_at helper ───────────────────────────────────────────────────────
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ── accounts ────────────────────────────────────────────────────────────────
-- One row per connected creator. Holds the X credentials + posting schedule.
-- SECRET: x_access_token must never be exposed to the browser. There are NO
-- anon RLS policies on this table, so the anon key cannot read it. Only Edge
-- Functions (service role) touch it.
create table if not exists public.accounts (
  id              uuid primary key default gen_random_uuid(),
  handle          text,                              -- e.g. "tweetforme" (no @)
  display_name    text,
  brand_material  text,                              -- seed content pasted by the user
  x_access_token  text,                              -- OAuth2 user token w/ tweet.write
  -- posting schedule: "N times per <period>"
  posts_per_period int  not null default 5,
  period           text not null default 'week'
                     check (period in ('day', 'week', 'month')),
  timezone         text not null default 'UTC',
  is_active        boolean not null default true,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

drop trigger if exists accounts_set_updated_at on public.accounts;
create trigger accounts_set_updated_at
  before update on public.accounts
  for each row execute function public.set_updated_at();

-- ── voice_profiles ──────────────────────────────────────────────────────────
-- The persisted, updatable "brand voice". `profile` holds the structured DNA
-- (hook patterns, phrases, tone scores, structures...). One current profile per
-- account; history is kept by inserting new rows and pointing the account at it.
create table if not exists public.voice_profiles (
  id           uuid primary key default gen_random_uuid(),
  account_id   uuid references public.accounts(id) on delete cascade,
  handle       text,
  archetype    text,
  summary      text,
  profile      jsonb not null default '{}'::jsonb,   -- full structured voice DNA
  samples      jsonb not null default '[]'::jsonb,   -- raw posts used to train
  tweets_analyzed int default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

drop trigger if exists voice_profiles_set_updated_at on public.voice_profiles;
create trigger voice_profiles_set_updated_at
  before update on public.voice_profiles
  for each row execute function public.set_updated_at();

create index if not exists voice_profiles_account_idx
  on public.voice_profiles (account_id);

-- ── posts ───────────────────────────────────────────────────────────────────
-- The content pipeline. Columns title/content/platform/status/scheduled_for and
-- engagement_* are exactly what the dashboard already reads (see transformPosts
-- in content-pipeline.html). The rest drive the orchestration loop.
--
-- status lifecycle:
--   pending   → generated by the LLM, awaiting human review
--   scheduled → APPROVED. Eligible for auto-publish at scheduled_for.
--   posted    → published to X
--   rejected  → declined by reviewer
--   draft     → sent back for revision / being regenerated
--   failed    → publish attempt errored (see error column); will retry
create table if not exists public.posts (
  id               uuid primary key default gen_random_uuid(),
  account_id       uuid references public.accounts(id) on delete set null,
  voice_profile_id uuid references public.voice_profiles(id) on delete set null,

  -- shown in the dashboard
  title            text,
  content          text not null,
  platform         text not null default 'Twitter / X',
  status           text not null default 'pending'
                     check (status in ('pending','scheduled','posted','rejected','draft','failed')),
  scheduled_for    timestamptz,

  -- engagement (text to match the dashboard's "12.5K" style display)
  engagement_views    text,
  engagement_likes    text,
  engagement_comments text,

  -- orchestration / auto-publish
  hold             boolean not null default false,   -- manual pause without losing approval
  approved_at      timestamptz,
  posted_at        timestamptz,
  x_tweet_id       text,
  x_url            text,
  error            text,
  publish_attempts int not null default 0,

  -- generation metadata (from the LLM)
  category    text,
  hook_type   text,
  why_it_fits text,

  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

drop trigger if exists posts_set_updated_at on public.posts;
create trigger posts_set_updated_at
  before update on public.posts
  for each row execute function public.set_updated_at();

-- When a post is approved, stamp approved_at automatically. This is the gate the
-- publisher relies on: only rows with status='scheduled' are ever sent.
create or replace function public.stamp_approved_at()
returns trigger language plpgsql as $$
begin
  if new.status = 'scheduled' and (old.status is distinct from 'scheduled') then
    new.approved_at = coalesce(new.approved_at, now());
  end if;
  return new;
end;
$$;

drop trigger if exists posts_stamp_approved_at on public.posts;
create trigger posts_stamp_approved_at
  before update on public.posts
  for each row execute function public.stamp_approved_at();

create index if not exists posts_status_idx        on public.posts (status);
create index if not exists posts_scheduled_for_idx on public.posts (scheduled_for);
create index if not exists posts_account_idx       on public.posts (account_id);
-- Hot path for the publisher: find approved, un-held posts that are due.
create index if not exists posts_due_idx
  on public.posts (scheduled_for)
  where status = 'scheduled' and hold = false;

-- ============================================================================
-- Row Level Security
-- ----------------------------------------------------------------------------
-- DEMO-GRADE, single-tenant. The dashboard talks to Supabase with the anon key,
-- so anon needs to read posts and flip their status (approve/reject/hold).
-- Generation + publishing run in Edge Functions with the service role, which
-- bypasses RLS entirely. `accounts` has NO anon policy => the X token is unreadable
-- from the browser.
--
-- TODO (multi-user): replace these with auth.uid()-scoped policies once sign-in
-- exists, and move status changes behind an Edge Function.
-- ============================================================================
alter table public.accounts       enable row level security;
alter table public.voice_profiles enable row level security;
alter table public.posts          enable row level security;

-- posts: anon can read + update (approve/reject/hold). Inserts/deletes are
-- service-role only (generation happens in an Edge Function).
drop policy if exists "posts anon read"   on public.posts;
drop policy if exists "posts anon update" on public.posts;
create policy "posts anon read"   on public.posts for select using (true);
create policy "posts anon update" on public.posts for update using (true) with check (true);

-- voice_profiles: anon may read (dashboard can show the voice). No anon writes.
drop policy if exists "voice anon read" on public.voice_profiles;
create policy "voice anon read" on public.voice_profiles for select using (true);

-- accounts: intentionally no anon policies. Service role only.
